### ISSUE TITLE
Book codes are missing!

### ISSUE THREAD

**Issue by ssia279** [PacktPublishing/Flutter-for-Beginners-Second-Edition#1]
It seems this repository doesn't contain the codes for the book. Please re-upload the project files again. Thanks.

**Comment by rajat-packt** [comment]
Hi @ssia279, 
Sorry that it took a while to look into this issue.
The code files for the book are located inside this directory: https://github.com/PacktPublishing/Flutter-for-Beginners-Second-Edition/tree/main/hello_world/lib
Additional files for chapter 11 are located here: https://github.com/PacktPublishing/Flutter-for-Beginners-Second-Edition/tree/main/hello_world/test/chapter_11

Can you take a look and verify if these were the files that were missing?
